name: supa_helper
description: "A clean and simple wrapper around Supabase for Flutter projects."
version: 0.1.0
homepage: https://github.com/Abdelrahmanyehia9/supa_helper.git
repository: https://github.com/Abdelrahmanyehia9/supa_helper.git
issue_tracker: https://github.com/Abdelrahmanyehia9/supa_helper/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  supabase_flutter: ^2.12.4
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


